import { initializeApp } from 'firebase/app';
import { getAuth, GoogleAuthProvider, FacebookAuthProvider } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';

// Default configuration from environment variables or local JSON
let firebaseConfig: any;

try {
  // Try to load from the JSON file generated by AI Studio
  // @ts-ignore
  firebaseConfig = await import('../firebase-applet-config.json').then(m => m.default);
} catch (e) {
  // Fallback to environment variables (useful for deployments where JSON is excluded)
  firebaseConfig = {
    // @ts-ignore
    projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,
    // @ts-ignore
    appId: import.meta.env.VITE_FIREBASE_APP_ID,
    // @ts-ignore
    apiKey: import.meta.env.VITE_FIREBASE_API_KEY,
    // @ts-ignore
    authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
    // @ts-ignore
    firestoreDatabaseId: import.meta.env.VITE_FIREBASE_FIRESTORE_DATABASE_ID,
    // @ts-ignore
    storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
    // @ts-ignore
    messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
    // @ts-ignore
    measurementId: import.meta.env.VITE_FIREBASE_MEASUREMENT_ID,
  };
}

const app = initializeApp(firebaseConfig);

export const auth = getAuth(app);
export const db = getFirestore(app, firebaseConfig.firestoreDatabaseId);

export const googleProvider = new GoogleAuthProvider();
export const facebookProvider = new FacebookAuthProvider();

export default app;
